# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20171210_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(blank=True, help_text="it's a string, which is shown in url address", verbose_name='Slug'),
        ),
    ]
