# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 02:46
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='visual_report',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
