# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photo_visual_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date'),
        ),
    ]
